server:
  port: 9000
  http2:
    enabled: true
spring:
  security:
    user:
      password: default-pass

logging:
  level:
    org:
      springframework:
        web: INFO
        data:
          mongodb:
            core:
              ReactiveMongoTemplate: DEBUG
    reactor:
      netty:
        http:
          client: DEBUG

springdoc:
  swagger-ui:
    path: /swagger-ui/index.html

jwt:
  signing:
    key:
      secret: mySecret