server:
  port: 9000
  http2:
    enabled: true
spring:
  security:
    user:
      password: default-pass
  kafka:
    bootstrap-servers: localhost:29092
    topic:
      authEvent: auth-events

logging:
  level:
    org:
      springframework:
        web: INFO
        data:
          mongodb:
            core:
              ReactiveMongoTemplate: DEBUG
    reactor:
      netty:
        http:
          client: DEBUG

springdoc:
  swagger-ui:
    path: /swagger-ui/index.html

jwt:
  signing:
    key:
      secret: mySecret


management:
  endpoints:
    web:
      exposure:
        include: 'prometheus'
  endpoint:
    prometheus:
      enabled: true